#!/usr/bin/env python3
// This script update varable and value of a collection
db.school.findOneAndUpdate(
        {name:"Holberton school"}, 
        {$set: {address:"972 Mission street"}}
        );
